name: "TechTrends - Package with Docker"

on:
  push:
    branches:
      - main # Trigger on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Run the action on the ubuntu-latest operating system
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4 # Checkout the repository

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Use GitHub secret for username
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Use GitHub secret for token

      - name: Build and push the TechTrends Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Set context to the project directory
          file: ./Dockerfile # Reference the Dockerfile for TechTrends application
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/techtrends:latest # Push with the tag techtrends:latest